spring:
  sql:
    init:
      mode: never
      schema-locations: classpath:org/springframework/batch/core/schema-h2.sql

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  datasource:
    url: jdbc:h2:file:./testdb;INIT=RUNSCRIPT FROM 'classpath:init.sql'
#    url: jdbc:h2:file:./testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rootbly.batchprac.domain