spring:
  sql:
    init:
      mode: never
      schema-locations: classpath:org/springframework/batch/core/schema-h2.sql

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  datasource:
    url: jdbc:h2:file:./testdb;INIT=RUNSCRIPT FROM 'classpath:insert_members_100k_single_file.sql'
    driver-class-name: org.h2.Driver
    username: sa
    password: