spring:
  sql:
    init:
      mode: never
      schema-locations: classpath:org/springframework/batch/core/schema-h2.sql

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  datasource:
    url: jdbc:h2:file:./testdb;INIT=RUNSCRIPT FROM 'classpath:init.sql'
#    url: jdbc:h2:file:./testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rootbly.batchprac.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.springframework.batch: DEBUG
    com.rootbly.batchprac: DEBUG