spring:
  application:
    name: spring-practice
  datasource:
    url: jdbc:mysql://localhost:3306/spring_practice?characterEncoding=UTF-8
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy